# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
geckolib_version=4.8.3
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.12
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=klyntars
mod_name=Klyntar Mod
mod_license=MIT
mod_version=1.0.0-1.20.1
mod_group_id=modKlyntar
mod_authors=MALDERA_LUIGI
mod_description=Klyntar/Venom mod portata a Minecraft Forge 1.20.1.
